---
title: "BpS Models"
author: ""
date: ""
output:
  word_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---
### This page:
+ Short introduction to the LANDFIRE program
+ Description of the Biophysical Settings, plus associated models and descriptions
+ Discussion of application scale

## LANDFIRE
[LANDFIRE](www.landfire.gov) is a multi-partner program that *"provides 20+ national geo-spatial layers (e.g. vegetation, fuel, disturbance, etc.), databases, and ecological models that are available to the public for the US and insular areas".*  

#### LANDFIRE BpS

[LANDFIRE Biophysical Settings ](https://www.landfire.gov/bps.php) represent vegetation that may have been dominant on the landscape just prior to Euro-American settlement.  They are based on [NatureServe's Ecological Systems](https://www.natureserve.org/conservation-tools/terrestrial-ecological-systems-united-states).  Biophysical Settings are:

1. Mapped.  For more information on the spatial data visit https://www.landfire.gov/bps.php.
2. Described
3. Modeled



One of the goals of LANDFIRE was to understand the condition of our ecosystems. The metric they created for this is called **"Vegetation Departure" (VDep)**. 

>**Vegetation departure** compares current vegetation structure and composition to "reference" structure and composition. 

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">

[**LANDFIRE Vegetation Departure (VDep)**](https://www.landfire.gov/vdep.php) indicates how different current vegetation on a landscape is from estimated reference conditions. VDep is based on:

* changes to species composition
* structural stage, 
* canopy closure (using methods originally described in the [Interagency Fire Regime Condition Class Guidebook (IFRCC))](https://www.landfire.gov/frcc/documents/FRCC_Guidebook_2010_final.pdf). 

**VDep vs. Interagency Fire Regime Condition Class Guidebook approach**

* [LANDFIRE VDep](https://www.landfire.gov/vdep.php) is based only on departure of current vegetation conditions from reference vegetation conditions
* [IFRCC Guidebook](https://www.landfire.gov/frcc/documents/FRCC_Guidebook_2010_final.pdf) approach includes departure of current fire regimes from those of the reference period
</div>
<br>

#### Steps to developing reference conditions:

1. **Classify and define the ecosystems.** LANDFIRE calls the historic ecosystems "Biophysical Settings", and used NatureServe's Ecological Systems classification as the "list".
2. The LANDFIRE team held expert workshops to:
    * **Describe the BpSs**, including their nested Succession Classes, up to 5 for each BpS including their canopy height, composition and percent cover. 
    * **Use state and transition modeling techniques** to get an estimate of how much of each succession class would have been on the landscape historically, (just prior to European settlement). The estimated amount of each succession class depends on the natural disturbance regimes that the experts input into the modeling software (just like you will be doing soon!).
    
From 2018 to 2019, TNC's LANDFIRE team led a review of these models and descriptions, adding some new features to all of them (e.g., disturbance information), and updating content for over 300 of them.  


<br>

###  Parts of a BpS

Each BpS (e.g., Montane Sagebrush Steppe) has 3 associated products:

1. Description 
2. State and transition model
3. Spatial data (not described here)

 <br>

#### Descriptions
Each BpS has an extensive description including information on:

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }

</style>


<div class="col2">
* Biophysical Setting Name and Number
* Map Zones the description covers
* Descriptive Geographic Range text
* Biophysical Site Description
* Disturbance description
* Descriptions of each succession class
* Relevant literature

</div>
 <br>

These were originally delivered as PDF documents (or in an Access Database).  These descriptions are now delivered as Microsoft Word documents.  

#### Models

When we refer to "models" we are essentially talking about the information contained in SyncroSim libraries. 

<br> 

What? 

<br>

We'll get to the SyncroSim and library parts in the coming pages, but in the meantime models are collections of information on:
1.  The "States" or succession classes of each BpS **AND**
2.  The Transitions:
    * Deterministic which essentially represents succession
    * Probabilitic which represents disturbances
    
Once the models are run you can obtain information on (among many other things):
1. Amounts of succession classes at the end of each year, in acres or proportion
2. How much disturbance happens over time, in acres or proportion


### Application scale of the models

Importantly, these models and descriptions were designed for use over large areas-not your back yard.  How large you ask?  It depends on many factors:

* How much review, and how comfortable users are with the information included in the models
* How important the decisions are, and how much risk is involved
* How much supporting information there is

<br>

### For more information
*  https://www.youtube.com/watch?v=e1BBcbImrrM&list=PLDFF9036BBFE46CE6&index=6&t=0s which is a Kori/Randy intro, 5 minutes.  Some features of SyncroSim may be different than what you see in the video based due to versioning.

