---
title: "Model Examples"
author: 
date: 
output:
  html_document:
    toc: yes
    toc_depth: 4
    toc_float: yes
---

### This page:
+ See how Jim Smith, Kori Blankenship and Randy Swaty attempted to modernize some BpS models, with a focus on the Sage-Steppe
+ Explore example models--then ask yourself "did they do a good job?"

## Context time
The models below are example models aimed at illustrating modification methods. They are not intended to be realistic ecological models…they are for illustration purposes. We hope that users will primarily use our models to learn, but also assume some people could be tempted to use them as “starter models”.  We’d rather they not do that as we are not experts in the actual ecosystems. We hope they serve to say "wow, these models are highly customizable".

## As you explore these models...
Ask yourself questions such as:

* Do these model modifications apply to my ecosystems?
* Could there be unintended consequences from these changes that trickle through the model?
* Do these modifications make the model more "realistic" or do they more serve to document new transitions that need more research or ???

## Three examples

<style>
div.blue { background-color:#cde6c8; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
### Montane Sage Steppe by Kori Blankenship

[Download Kori's notes here](https://tnc.box.com/s/ah8wy1p79ords5rl1esf74k0raxh6ivx)

**Model Identifier**
This model is based on the LANDFIRE 11260_1_7_8_9_10_19 BpS model and description and was modified based on several sources to represent current conditions. The primary source was the unpublished “Mountain Big Sagebrush – With Juniper” model created by Miles Hemstrom for the Blue Mtns. 

**Original Model Description**
The Inter-Mountain Basins Montane Sagebrush Steppe is found on moderately to deep soils that are well drained and predominantly Mollisols across the northwestern US. It typically occurs as elevations ranging from 3,250 to 10,000ft depending partially on the geography.
Mountain big sagebrush (Artemisia tridentata spp. vaseyana) is the dominant big sagebrush subspecies. Other indicator species include antelope bitterbrush, Idaho fescue, Rough fescue, bluebunch wheatgrass, Columbia needlegrass and Sandberg bluegrass.


**Model Modification Steps**

* Added three new states to represent invasion of juniper into sagebrush and the presence of invasive annual grasses with and without tress. 
* Added 4 new transitions:
    *	**Encroachment represents** Juniper encroachment into the late seral native shrubland
    *	**Grazing** represents the impact of moderate livestock grazing and does not cause a state change
    *	**GrazeDegrade** represents the combined effects of heavy livestock grazing within two years post-fire disturbance which causes a transition to an exotic state
    *	Recovery represents natural recovery of native vegetation from exotic vegetation
* Added new transitions to and from the new states (see full description for details)
* Added mixed fire to native sage states
* Updated replacement fire probabilities
* Used initial conditions based on LANDFIRE 2014 succession class data
* Adjusted the Run and Time Since Transition settings
</div>
<br>



### Central Mixed Grass Prairie by Jim Smith


**Model Identifier**
Note that the modifications illustrated in this example were applied to a locally-modified LANDFIRE BpS model 11320_32_34_35-Central Mixed Grass Prairie . You do not have to begin the modification process with a LANDFIRE model. You can utilize any model that serves as a useful starting point for your project.

**Original Model Description**
This type occurs on sandy loam, loamy, or clayey upland sites of the southern Great Plains. It is dominated by midgrasses with some mix of tall and short grass.  

**Modification Goal**
Investigate how grazing management may have changed landscape conditions since pre-European settlement. 

**Model Modification Steps**

* Adjust Run Parameters  
    * The LANDFIRE Reference Condition model as downloaded had 0% pixels in Early Open class so we used 1% (100 acres) as the initial condition for this class and lowered the highest class by 1% to keep the total at 100%.
    * Change timesteps to 100 years (assuming grazing practices changed approximately 100 years ago).
    * Changed number of iterations to 5 to increase turnaround time for runs, but would likely increase that number to 10 or more operationally.
    * Changed the number of cells to 10,000 and cell size to 1 acre to represent a 10,000 landscape. 
* Altered transitions
    * Added a prairie Restoration treatment transition to the Late 3 All state class to represent restarting overgrazed lands at the Early       * Open regeneration succession state using management techniques such as plowing, seeding, fertilizing, etc. Budget constrains this treatment to a 5% frequency. 
    * Added a Livestock grazing transition to the Late 2 Closed state class that moves pixels to the Late 3 All state class at 10% frequency. This transition represents overgrazing a mature prairie. 
    * Added a Livestock grazing transition to the Late 1 Closed state class that moves pixels to the Late 3 All state class at a lower frequency (5%) because the Late 1 Closed state is more difficult to overgraze. This transition represents overgrazing a mature prairie. 
    * Added a Livestock Grazing transition to the Late 3 All overgrazed succession state that maintains that succession state by continuing to overgraze at a frequency of 20%.  
    
<br>

### Laurentian-Acadian Northern Hardwoods Forest - Hemlock by Randy Swaty



**Model Identifier**
The starter model for this example was 13021_41_50_51, the Laurentian-Acadian Northern Hardwoods Forest - Hemlock that occurs in Minnesota, Wisconsin and Michigan.  

**Original Model Description**
These uneven-aged forests occur on coarse-textured ground and end moraines lying predominantly north of the tension zone and were dominated by a mix of sugar maple, hemlock, yellow birch, eastern white pine, balsam fir, quaking aspen and paper birch depending on the location (e.g., beech is restricted to eastern part of the range).  

**Model Modification Steps**

* Added 2 new states
    * "Maple Monoculture"
    * Beech  resprout
* Added new transitions
    * single tree selection–leads to maple monoculture
    * clearcut
    * deer
    * beech bark disease
    * ecological harvest 
* Set initial conditions to match current dominance by the Maple Monoculture class



