---
title: "Review Your Models"
author: 
date:
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---
*Working, formatting needs consistency Randy Videos: 1)getting the models, putting them in syncrosim 2) how to review the model*

### This page:
+ Get a description and model by:
    + understanding and finding your Map Zone
    + downloading a BpS description
    + loading a model into SyncroSim
    
We will walk through the process with the Inter-Mountain Basins Montane Sagebrush Steppe Biophysical Setting of the Northwestern United States.  **This ecosystem will be the subject of later tutorials**. 


### Understand and find your Map Zone

First you need to know that there are hundreds of Biophysical Settings in the United States, and some of them occur in more than one Map Zone.  What is a Map Zone?  It's basically a product delivery and summary polygon.  The polygons are from the National Landcover Database Program (see https://www.mrlc.gov/national-land-cover-database-nlcd-2016).  

Pan, zoom, scroll to your area of interest, then hover over the Map Zone you need the number for.  A tooltip will pop up with that info.  Take note of it for the next step. 

**For our ecosystem of interest we are looking in eastern Oregon, or Map Zone 9.**

<br>

```{r echo=FALSE, message=FALSE, warning=FALSE}
htmltools::tags$iframe(title = "My embedded document", src = "leafletSIM2carto.html", frameborder = "0", width = "100%", height="400")
```

<br>

### Download a BpS Description
We have a website (http://landfirereview.org/search.php) where you can go to search for and retrieve LANDFIRE BpS model descriptions.  

**For this exercise please search for and retrieve the description for Inter-Mountain Basins Montane Sagebrush Steppe that covers Map Zone 9 (may cover multiple Map Zones).**

### Load your model
Once you have SyncroSim installed, and the LANDFIRE Package loaded, you will go through a few steps to isolate one model to work with. 

**You can view and print the instructions [here](./isolateModel.html).**

***

### For more information

*  How to Alter and Run a LANDFIRE Model in ST-Sim, https://www.youtube.com/watch?v=XUUm-RG4eK0&list=PLDFF9036BBFE46CE6&index=7&t=0s

Some features of SyncroSim may be different than what you see in the video due to versioning.


.