---
title: "LANDFIRE Vegetation Modeling"
author:
date: 
output:
  html_document:
    toc: true
    toc_float: true
---
### On this page you will find: 
+ an introduction to biophysical setting models
+ a short video that will provide context for this modeling framework including instructions on registering and downloading SyncroSim

## Welcome
Welcome to the LANDFIRE vegetation modeling site. We created this site to help you harness the potential of the modeling framework to accomplish your management and restoration objectives. We recognize the importance of having the best resources to accomplish your goals. The LANDFIRE team is continually improving the LANDFIRE product suite to help you get the right data.

We designed this website as a resource for both new and seasoned BpS users. You can skip ahead to the useful videos and sections, or navitate through each tab and section as it suites you. We stuck with one example in these tutorials to remain consistent and help you follow our model “story”. We’ll be exploring the Montane Sagebush Steppe Ecosystem throughout this site.


## Why model?  
#### Modeling biophysical models provide a framework for:  

1. Simulating disturbances and testing potential management strategies (before allocating time or money in on the ground operations) 
2. Modeling vegetation characteristics on the landscape  
3. Making predictions of future landscape conditions
<br>


## Start here
This video will provide some context about biophysical modeling framework and a discussion of the power of using LANDFIRE historical vegetation models in your work. We'll finish with a short demonstration of how to install SyncroSim on your machine, 


