---
title: "Review Your Models"
author: 
date:
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
---
*Working, formatting needs consistency Randy Videos: 1)getting the models, putting them in syncrosim 2) how to review the model*

## The basic process
Our hope is that LANDFIRE Biophysical Settings models help jumpstart your modeling work.  When we work with landscapes we often modify a LANDFIRE reference condition model instead of starting from scratch.  To do this (and to learn about the LANDFIRE modeling approach) you will:

1. Figure out which Map Zone your ecosystem is in
2. Get three things: a) the model description,  b) software and c) the LANDFIRE model
2. Review the description
3. Run and explore the model
4. Start to document how you need to modify the refernce condition model so that it better represents the ecological and management processes of today (e.g., add fire suppression and thinning)

We will walk through the process with the Inter-Mountain Basins Montane Sagebrush Steppe Biophysical Setting of the Northwestern United States.  

### 1. Find your Map Zone of interest here:

First you need to know that there are hundreds of Biophysical Settings in the United States, and some of them occur in more than one Map Zone.  What is a Map Zone?  It's basically a product delivery and summary polygon.  The polygons are from the National Landcover Database Program (see https://www.mrlc.gov/national-land-cover-database-nlcd-2016).  

Pan, zoom, scroll to your area of interest, then hover over the Map Zone you need the number for.  A tooltip will pop up with that info.  Take note of it for the next step. For our ecosystem of interest we are looking in eastern Oregon, or Map Zone 9.

```{r echo=FALSE, message=FALSE, warning=FALSE}
htmltools::tags$iframe(title = "My embedded document", src = "leafletSIM2carto.html", frameborder = "0", width = "100%", height="900")
```
<br>

### 2a. Get a LANDFIRE description 
We have a website (http://landfirereview.org/search.php) where you can go to search for and retrieve LANDFIRE BpS model descriptions.  For this exercise please search for and retrieve the description for Inter-Mountain Basins Montane Sagebrush Steppe that covers Map Zone 9 (may cover multiple Map Zones).

### 2b. Get the software
We use SyncroSim by Apex RMS (http://www.apexrms.com/) as our modeling software.  It's free to download from https://syncrosim.com/download/.   

### 2c. Get the model of interest
Now that you have the software installed, we will walk you through getting 



.