---
title: "Welcome page"
author: "Megan Dettenmaier"
date: "7/6/2020"
output:
  html_document: null
  pdf_document: default
  toc: yes
  toc_depth: 4
  toc_float: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Hello and welcome to the LANDFIRE vegetation modeling site. We created this site to help you harness the potential of the modeling framework to accomplish your management and restoration objectives. We recognize the importance of having the best resources to accomplish your goals…and here at LANDFIRE we are continually improving our products to get you the data you need. 

#### So, what will you learn? Here’s just a sample:  

1. We’ll discuss how LANDFIRE historical vegetation models can jumpstart your research, management planning and understanding of both current and future ecosystems 
2. We’ll help you navigate the Syncrosim biophysical vegetation modeling framework 
3. And finally, we’ll offer real life, on the ground examples of the models in action and demonstrate how modeling perturbations in the environment can inform and direct effective management actions 

#### Why integrate this into your current work? 

This framework provides a national baseline for assessing current vegetation conditions while accounting for historical ecology. Integrating this knowledge with our current projections of climate and other factors can has the potential to improve the way we manage land while providing some ecological context. This modeling framework can help you making predictions about future landscape conditions.  For example, you may be interested in understanding how an insect invasion will impact a specific region, with the right data and a little bit of time, this program can help you make predictions and plan for the future.  

#### What you will learn

1. We'll show you how to accessing the data on landfire.gov
2. We'll walk you through how to run and adapt the models
3. And finally we'll show you how to interpret the results

#### Let's get started

1. To get the process rolling you need to install syncrosim on your machine - but before you do that, you need to register with syncrosim, go to - https://syncrosim.com/ 

2. Then you’ll go to download (that's emailed to you (RIGHT?)), and find the version of Syncrosim that’s appropriate for your hardware.  

3. Next you’ll head on over to the LANDFIRE site and download the Master ST-Sim database.  https://www.landfire.gov/national_veg_models_op2.php   

4. And finally, open Syncrosim, go to file, open library, locate the unzipped Master St-Sim database that you just downloaded. Once you do that, you’re ready to get started.  

#### Use this website

We designed this website as a resource for both new and seasoned BpS users. You can skip ahead to the useful videos and sections, or navitate through each tab and section as it suites you. We stuck with one example in these tutorials to remain consistent and help you follow our model "story". We'll be exploring the Sage Steppe BpS throughout this site. 

Either way, we hope you find our website useful and most importantly, we hope you use these BpS models to their fullest extent - Your next step is to find and organize your model. (insert link)